[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "simonsays"
authors = [{name = "DaanVervacke", email = "daan.vervacke@student.vives.be"}]
dynamic = ["version", "description"]
